In [34]:
import requests 
import numpy as np
import pandas as pd
from pandas.io.json import json_normalize  

url = "https://www.fema.gov/api/open/v1/DisasterDeclarationsSummaries?$top=10&$orderby=disasterNumber&$format=json"
apiResponse = requests.get(url)
responseJson = apiResponse.json()

df = json_normalize(responseJson, 'DisasterDeclarationsSummaries')
print(df)

            declarationDate declaredCountyArea      disasterCloseOutDate  \
0  1953-05-02T00:00:00.000Z                     1954-06-01T00:00:00.000Z
1  1953-05-15T00:00:00.000Z                     1958-01-01T00:00:00.000Z
2  1953-05-29T00:00:00.000Z                     1960-02-01T00:00:00.000Z
3  1953-06-02T00:00:00.000Z                     1956-02-01T00:00:00.000Z
4  1953-06-06T00:00:00.000Z                     1955-12-01T00:00:00.000Z
5  1953-06-09T00:00:00.000Z                     1956-03-30T00:00:00.000Z
6  1953-06-11T00:00:00.000Z                     1956-06-01T00:00:00.000Z
7  1953-06-11T00:00:00.000Z                     1955-11-01T00:00:00.000Z
8  1953-06-19T00:00:00.000Z                     1958-01-01T00:00:00.000Z
9  1953-07-02T00:00:00.000Z                     1956-02-01T00:00:00.000Z

   disasterNumber disasterType  fyDeclared                              hash  \
0               1           DR        1953  1dcb40d0664d22d39de787b706b0fa69
1               2           DR        1953  61612cea5779e361b429799098974b6a
2               3           DR        1953  86f3e47785cb7acc51364d4535d36101
3               4           DR        1953  1dbe5937a01fc74c8e699912e3f555cb
4               5           DR        1953  7439b90b81816e385768c0d49b832af5
5               6           DR        1953  2208518c84c44f8e4164248d47f89ead
6               7           DR        1953  1118ef337c5993b0e939b63ea4440c69
7               8           DR        1953  0fca0037b160f9ae81f6d4246a81a7e6
8               9           DR        1953  5cc3af111f94e26100fca2605a9d0d26
9              11           DR        1953  9d856a5b709986eb302e605ffbb10c7b

   hmProgramDeclared  iaProgramDeclared                        id  \
0               True               True  5d1bbd8c8bdcfa6efb32fd8d
1               True               True  5d1bbd8c8bdcfa6efb32fd8e
2               True               True  5d1bbd8c8bdcfa6efb32fd8f
3               True               True  5d1bbd8c8bdcfa6efb32fd91
4               True               True  5d1bbd8c8bdcfa6efb32fd90
5               True               True  5d1bbd8c8bdcfa6efb32fd92
6               True               True  5d1bbd8d8bdcfa6efb32fd94
7               True               True  5d1bbd8d8bdcfa6efb32fd93
8               True               True  5d1bbd8d8bdcfa6efb32fd96
9               True               True  5d1bbd8d8bdcfa6efb32fd95

   ihProgramDeclared         incidentBeginDate           incidentEndDate  \
0              False  1953-05-02T00:00:00.000Z  1953-05-02T00:00:00.000Z
1              False  1953-05-15T00:00:00.000Z  1953-05-15T00:00:00.000Z
2              False  1953-05-29T00:00:00.000Z  1953-05-29T00:00:00.000Z
3              False  1953-06-02T00:00:00.000Z  1953-06-02T00:00:00.000Z
4              False  1953-06-06T00:00:00.000Z  1953-06-06T00:00:00.000Z
5              False  1953-06-09T00:00:00.000Z  1953-06-09T00:00:00.000Z
6              False  1953-06-11T00:00:00.000Z  1953-06-11T00:00:00.000Z
7              False  1953-06-11T00:00:00.000Z  1953-06-11T00:00:00.000Z
8              False  1953-06-19T00:00:00.000Z  1953-06-19T00:00:00.000Z
9              False  1953-07-02T00:00:00.000Z  1953-07-02T00:00:00.000Z

  incidentType               lastRefresh  paProgramDeclared placeCode state  \
0      Tornado  2019-07-02T20:24:44.403Z               True              GA
1      Tornado  2019-07-02T20:24:44.708Z               True              TX
2        Flood  2019-07-02T20:24:44.708Z               True              LA
3      Tornado  2019-07-02T20:24:44.969Z               True              MI
4        Flood  2019-07-02T20:24:44.968Z               True              MT
5      Tornado  2019-07-02T20:24:44.969Z               True              MI
6      Tornado  2019-07-02T20:24:45.189Z               True              MA
7        Flood  2019-07-02T20:24:45.189Z               True              IA
8        Flood  2019-07-02T20:24:45.190Z               True              TX
9         Fire  2019-07-02T20:24:45.189Z               True              NH

                      title
0                   TORNADO
1  TORNADO & HEAVY RAINFALL
2                     FLOOD
3                   TORNADO
4                    FLOODS
5                   TORNADO
6                   TORNADO
7                     FLOOD
8                     FLOOD
9               FOREST FIRE

In [40]:
import requests 
import numpy as np
import pandas as pd
from pandas.io.json import json_normalize  

url = "https://www.fema.gov/api/open/v1/DisasterDeclarationsSummaries?$top=10&$orderby=disasterNumber&$format=json"
url2 = "https://www.fema.gov/api/open/v1/IndividualAssistanceHousingRegistrantsLargeDisasters?$top=10&$orderby=disasterNumber&$format=json"
apiResponse = requests.get(url)
apiResponse2 = requests.get(url2)
responseJson = apiResponse.json()
responseJson2 = apiResponse2.json()

df = json_normalize(responseJson, 'DisasterDeclarationsSummaries')
df2 = json_normalize(responseJson2, 'IndividualAssistanceHousingRegistrantsLargeDisasters')
print(df2)

     censusBlockId censusYear     damagedCity damagedStateAbbreviation  \
0  482013129002017       2017         HOUSTON                       TX
1  484579502005051       2017       WOODVILLE                       TX
2  483550054092001       2017  CORPUS CHRISTI                       TX
3  482014334001003       2017         HOUSTON                       TX
4  482013321001024       2017         HOUSTON                       TX
5  482917002001042       2017       CLEVELAND                       TX
6  481990303001365       2017         KOUNTZE                       TX
7  483550022004005       2017  CORPUS CHRISTI                       TX
8  481576706011001       2017   MISSOURI CITY                       TX
9  483396904024005       2017        MAGNOLIA                       TX

  damagedZipCode  destroyed disasterNumber  floodDamage  floodInsurance  \
0          77004      False           4332        False            True
1          75979      False           4332         True           False
2          78413      False           4332        False           False
3          77036      False           4332        False           False
4          77033      False           4332        False           False
5          77327      False           4332        False           False
6          77625      False           4332        False            True
7          78411      False           4332        False           False
8          77489      False           4332        False           False
9          77354      False           4332        False           False

   foundationDamage  ... replacementAssistanceEligible  residenceType  \
0             False  ...                         False   House/Duplex
1             False  ...                         False    Mobile Home
2             False  ...                         False   House/Duplex
3             False  ...                         False      Apartment
4             False  ...                         False   House/Duplex
5             False  ...                         False    Mobile Home
6             False  ...                         False    Mobile Home
7             False  ...                         False   House/Duplex
8             False  ...                         False   House/Duplex
9             False  ...                         False    Mobile Home

  roofDamage  roofDamageAmount   rpfvl sbaEligible  specialNeeds tsaCheckedIn  \
0      False               NaN     NaN       False         False        False
1      False               NaN  846.95       False         False        False
2      False               NaN  213.87       False         False        False
3      False               NaN     NaN       False         False        False
4      False               NaN     NaN       False         False        False
5      False               NaN     NaN       False         False        False
6       True             54.12  210.44       False         False        False
7      False               NaN     NaN       False         False        False
8      False               NaN     NaN       False         False        False
9       True             61.20  420.90       False         False        False

   tsaEligible  waterLevel
0        False         NaN
1        False         6.0
2        False         0.0
3        False         NaN
4         True         0.0
5         True        24.0
6        False         0.0
7        False         NaN
8        False         0.0
9        False         0.0

[10 rows x 41 columns]

In [45]:
import requests 
import numpy as np
import pandas as pd
from pandas.io.json import json_normalize  

url = "https://www.fema.gov/api/open/v1/DisasterDeclarationsSummaries?$top=10&$orderby=disasterNumber&$format=json"
url2 = "https://www.fema.gov/api/open/v1/IndividualAssistanceHousingRegistrantsLargeDisasters?$top=10&$orderby=disasterNumber&$format=json"
apiResponse = requests.get(url)
apiResponse2 = requests.get(url2)
responseJson = apiResponse.json()
responseJson2 = apiResponse2.json()

df = json_normalize(responseJson, 'DisasterDeclarationsSummaries')
df2 = json_normalize(responseJson2, 'IndividualAssistanceHousingRegistrantsLargeDisasters')
frames = [df, df2]
pd.concat(frames, join='outer', keys=['disasterNumber'])

                           declarationDate declaredCountyArea  \
disasterNumber 0  1953-05-02T00:00:00.000Z
               1  1953-05-15T00:00:00.000Z
               2  1953-05-29T00:00:00.000Z
               3  1953-06-02T00:00:00.000Z
               4  1953-06-06T00:00:00.000Z
               5  1953-06-09T00:00:00.000Z
               6  1953-06-11T00:00:00.000Z
               7  1953-06-11T00:00:00.000Z
               8  1953-06-19T00:00:00.000Z
               9  1953-07-02T00:00:00.000Z

                      disasterCloseOutDate  disasterNumber disasterType  \
disasterNumber 0  1954-06-01T00:00:00.000Z               1           DR
               1  1958-01-01T00:00:00.000Z               2           DR
               2  1960-02-01T00:00:00.000Z               3           DR
               3  1956-02-01T00:00:00.000Z               4           DR
               4  1955-12-01T00:00:00.000Z               5           DR
               5  1956-03-30T00:00:00.000Z               6           DR
               6  1956-06-01T00:00:00.000Z               7           DR
               7  1955-11-01T00:00:00.000Z               8           DR
               8  1958-01-01T00:00:00.000Z               9           DR
               9  1956-02-01T00:00:00.000Z              11           DR

                  fyDeclared                              hash  \
disasterNumber 0        1953  1dcb40d0664d22d39de787b706b0fa69
               1        1953  61612cea5779e361b429799098974b6a
               2        1953  86f3e47785cb7acc51364d4535d36101
               3        1953  1dbe5937a01fc74c8e699912e3f555cb
               4        1953  7439b90b81816e385768c0d49b832af5
               5        1953  2208518c84c44f8e4164248d47f89ead
               6        1953  1118ef337c5993b0e939b63ea4440c69
               7        1953  0fca0037b160f9ae81f6d4246a81a7e6
               8        1953  5cc3af111f94e26100fca2605a9d0d26
               9        1953  9d856a5b709986eb302e605ffbb10c7b

                  hmProgramDeclared  iaProgramDeclared  \
disasterNumber 0               True               True
               1               True               True
               2               True               True
               3               True               True
               4               True               True
               5               True               True
               6               True               True
               7               True               True
               8               True               True
               9               True               True

                                        id  ihProgramDeclared  \
disasterNumber 0  5d1bbd8c8bdcfa6efb32fd8d              False
               1  5d1bbd8c8bdcfa6efb32fd8e              False
               2  5d1bbd8c8bdcfa6efb32fd8f              False
               3  5d1bbd8c8bdcfa6efb32fd91              False
               4  5d1bbd8c8bdcfa6efb32fd90              False
               5  5d1bbd8c8bdcfa6efb32fd92              False
               6  5d1bbd8d8bdcfa6efb32fd94              False
               7  5d1bbd8d8bdcfa6efb32fd93              False
               8  5d1bbd8d8bdcfa6efb32fd96              False
               9  5d1bbd8d8bdcfa6efb32fd95              False

                         incidentBeginDate           incidentEndDate  \
disasterNumber 0  1953-05-02T00:00:00.000Z  1953-05-02T00:00:00.000Z
               1  1953-05-15T00:00:00.000Z  1953-05-15T00:00:00.000Z
               2  1953-05-29T00:00:00.000Z  1953-05-29T00:00:00.000Z
               3  1953-06-02T00:00:00.000Z  1953-06-02T00:00:00.000Z
               4  1953-06-06T00:00:00.000Z  1953-06-06T00:00:00.000Z
               5  1953-06-09T00:00:00.000Z  1953-06-09T00:00:00.000Z
               6  1953-06-11T00:00:00.000Z  1953-06-11T00:00:00.000Z
               7  1953-06-11T00:00:00.000Z  1953-06-11T00:00:00.000Z
               8  1953-06-19T00:00:00.000Z  1953-06-19T00:00:00.000Z
               9  1953-07-02T00:00:00.000Z  1953-07-02T00:00:00.000Z

                 incidentType               lastRefresh  paProgramDeclared  \
disasterNumber 0      Tornado  2019-07-02T20:24:44.403Z               True
               1      Tornado  2019-07-02T20:24:44.708Z               True
               2        Flood  2019-07-02T20:24:44.708Z               True
               3      Tornado  2019-07-02T20:24:44.969Z               True
               4        Flood  2019-07-02T20:24:44.968Z               True
               5      Tornado  2019-07-02T20:24:44.969Z               True
               6      Tornado  2019-07-02T20:24:45.189Z               True
               7        Flood  2019-07-02T20:24:45.189Z               True
               8        Flood  2019-07-02T20:24:45.190Z               True
               9         Fire  2019-07-02T20:24:45.189Z               True

                 placeCode state                     title
disasterNumber 0              GA                   TORNADO
               1              TX  TORNADO & HEAVY RAINFALL
               2              LA                     FLOOD
               3              MI                   TORNADO
               4              MT                    FLOODS
               5              MI                   TORNADO
               6              MA                   TORNADO
               7              IA                     FLOOD
               8              TX                     FLOOD
               9              NH               FOREST FIRE